# Используем базовый образ Python
FROM python:3.9-slim

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файл скрипта в контейнер
COPY time.py /app/time.py

# Определяем команду запуска контейнера
CMD ["python", "/app/time.py"]
